name: CI/CD Docker Nginx

on:
  push:
    branches:
      - 'main'
    paths:
      - 'index.html'  # Este pipeline se ejecutará cada vez que se actualice index.html
  pull_request:
    paths:
      - 'index.html'  # También se ejecutará en PRs que afecten index.html

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Chequear el código desde GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker (si no lo está ya)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t myusername/nginx:latest .
          
      # Paso 4: Iniciar sesión en Docker Hub (para subir la imagen)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Subir la imagen Docker a Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push myusername/nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push  # Este job depende de que el build haya terminado exitosamente
    steps:
      - name: SSH into server and pull the new Docker image
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull myusername/nginx:latest
            docker stop nginx-container || true  # Detener el contenedor si ya existe
            docker rm nginx-container || true    # Eliminar el contenedor
            docker run -d --name nginx-container -p 80:80 myusername/nginx:latest
